apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: trendappdeployment
  labels:
    app: trendapp 
spec: 
  replicas: 2 
  selector:
    matchLabels:
      app: trendapp 
  template: 
    metadata: 
      labels: 
        app: trendapp 
    spec: 
     containers: 
       - image: srisatyap/dev:22
         name: trendapp
         ports: 
           - containerPort: 3000 
      