apiVersion: v1 
kind: Service 
metadata: 
  name: trendservice 
  labels: 
    name: trend-svc
spec: 
  selector:
    app: trendapp 
  type: LoadBalancer 
  ports: 
    - port: 80 
      targetPort: 3000